name: 'Serverless with Python Requirements - Only Changed Functions'
description: 'Javascript action that runs a Serverless deploy using the serverless-python-requirements plugin.'

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'fast-forward'
  color: 'red'
